version: "3.1"
services:
  account-service:
    image: account-service
#    ports:
#      - "2222:2222"
    networks:
      - cloud
  customer-service:
    image: customer-service
#    ports:
#      - "3333:3333"
    networks:
      - cloud
  discovery-service:
    image: discovery-service
    ports:
      - "8761:8761"
    networks:
      - cloud
  gateway-service:
    image: gateway-service
    ports:
      - "8765:8765"
    networks:
      - cloud

networks:
  cloud: