version: "3.1"
services:
#  account-service:
#    image: account-service
#    ports:
#      - "2222:2222"
#    networks:
#      - overlay
#  customer-service:
#    image: customer-service
#    ports:
#      - "3333:3333"
#    networks:
#      - overlay
#  discovery-service:
#    image: discovery-service
#    ports:
#      - "8761:8761"
#    networks:
#      - overlay
  gateway-service:
    image: gateway-service
    ports:
      - "8765:8765"
    networks:
      - overlay

networks:
  overlay: